package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClassifyType generated by hbm2java
 */
@Entity
@Table(name="classify_type"
    ,catalog="networkpublicopinionmap"
)
public class ClassifyType  implements java.io.Serializable {


     private String classifyId;
     private String classifyName;
     private String classifyContent;
     private Double sumWordFre;
     private Double sumWord;
     private Double sumText;

    public ClassifyType() {
    }

	
    public ClassifyType(String classifyId) {
        this.classifyId = classifyId;
    }
    public ClassifyType(String classifyId, String classifyName, String classifyContent, Double sumWordFre, Double sumWord) {
       this.classifyId = classifyId;
       this.classifyName = classifyName;
       this.classifyContent = classifyContent;
       this.sumWordFre = sumWordFre;
       this.sumWord = sumWord;
    }
   
     @Id 

    
    @Column(name="classify_id", unique=true, nullable=false, length=32)
    public String getClassifyId() {
        return this.classifyId;
    }
    
    public void setClassifyId(String classifyId) {
        this.classifyId = classifyId;
    }

    
    @Column(name="classify_name", length=32)
    public String getClassifyName() {
        return this.classifyName;
    }
    
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName;
    }

    
    @Column(name="classify_content", length=65535)
    public String getClassifyContent() {
        return this.classifyContent;
    }
    
    public void setClassifyContent(String classifyContent) {
        this.classifyContent = classifyContent;
    }

    
    @Column(name="sum_word_fre", precision=22, scale=0)
    public Double getSumWordFre() {
        return this.sumWordFre;
    }
    
    public void setSumWordFre(Double sumWordFre) {
        this.sumWordFre = sumWordFre;
    }

    
    @Column(name="sum_word", precision=22, scale=0)
    public Double getSumWord() {
        return this.sumWord;
    }
    
    public void setSumWord(Double sumWord) {
        this.sumWord = sumWord;
    }

    @Column(precision=22, scale=0)
	public Double getSumText() {
		return sumText;
	}


	public void setSumText(Double sumText) {
		this.sumText = sumText;
	}




}


