package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DataDictionary generated by hbm2java
 */
@Entity
@Table(name="data_dictionary"
    ,catalog="networkpublicopinionmap"
)
public class DataDictionary  implements java.io.Serializable {


     private String dataDictionaryId;
     private DataType dataType;
     private String dicKey;
     private String dicValue;
     private String section;

    public DataDictionary() {
    }

	
    public DataDictionary(String dataDictionaryId) {
        this.dataDictionaryId = dataDictionaryId;
    }
    public DataDictionary(String dataDictionaryId, DataType dataType, String dicKey, String dicValue, String section) {
       this.dataDictionaryId = dataDictionaryId;
       this.dataType = dataType;
       this.dicKey = dicKey;
       this.dicValue = dicValue;
       this.section = section;
    }
   
     @Id 

    
    @Column(name="data_dictionary_id", unique=true, nullable=false, length=32)
    public String getDataDictionaryId() {
        return this.dataDictionaryId;
    }
    
    public void setDataDictionaryId(String dataDictionaryId) {
        this.dataDictionaryId = dataDictionaryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id")
    public DataType getDataType() {
        return this.dataType;
    }
    
    public void setDataType(DataType dataType) {
        this.dataType = dataType;
    }

    
    @Column(name="dic_key", length=100)
    public String getDicKey() {
        return this.dicKey;
    }
    
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey;
    }

    
    @Column(name="dic_value", length=200)
    public String getDicValue() {
        return this.dicValue;
    }
    
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue;
    }

    
    @Column(name="section", length=50)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }




}


