package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataType generated by hbm2java
 */
@Entity
@Table(name="data_type"
    ,catalog="networkpublicopinionmap"
)
public class DataType  implements java.io.Serializable {


     private String typeId;
     private String typeName;
     private String featureVector;
     private String state;
     private Set<DataDictionary> dataDictionaries = new HashSet<DataDictionary>(0);

    public DataType() {
    }

	
    public DataType(String typeId) {
        this.typeId = typeId;
    }
    public DataType(String typeId, String typeName, String featureVector, String state, Set<DataDictionary> dataDictionaries) {
       this.typeId = typeId;
       this.typeName = typeName;
       this.featureVector = featureVector;
       this.state = state;
       this.dataDictionaries = dataDictionaries;
    }
   
     @Id 

    
    @Column(name="type_id", unique=true, nullable=false, length=32)
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    
    @Column(name="type_name", length=50)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    
    @Column(name="feature_vector", length=65535)
    public String getFeatureVector() {
        return this.featureVector;
    }
    
    public void setFeatureVector(String featureVector) {
        this.featureVector = featureVector;
    }

    
    @Column(name="state", length=20)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataType")
    public Set<DataDictionary> getDataDictionaries() {
        return this.dataDictionaries;
    }
    
    public void setDataDictionaries(Set<DataDictionary> dataDictionaries) {
        this.dataDictionaries = dataDictionaries;
    }




}


