package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DataEvent generated by hbm2java
 */
@Entity
@Table(name="data_event"
    ,catalog="networkpublicopinionmap"
)
public class DataEvent  implements java.io.Serializable {


     private String dataEventId;
     private DataSource dataSource;
     private Event event;
     private String state;

    public DataEvent() {
    }

	
    public DataEvent(String dataEventId) {
        this.dataEventId = dataEventId;
    }
    public DataEvent(String dataEventId, DataSource dataSource, Event event, String state) {
       this.dataEventId = dataEventId;
       this.dataSource = dataSource;
       this.event = event;
       this.state = state;
    }
   
     @Id 

    
    @Column(name="data_event_id", unique=true, nullable=false, length=32)
    public String getDataEventId() {
        return this.dataEventId;
    }
    
    public void setDataEventId(String dataEventId) {
        this.dataEventId = dataEventId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="data_source_id")
    public DataSource getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="state", length=20)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


