package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datasource1 generated by hbm2java
 */
@Entity
@Table(name="datasource1"
    ,catalog="networkpublicopinionmap"
)
public class Datasource1  implements java.io.Serializable {


     private String dataId;
     private String dataType;
     private String dataUrl;
     private String dataTitle;
     private String dataContent;
     private Date publishTime;
     private String dataSourceWebsite;
     private Date grabTime;
     private String classify;
     private String isFenci;
     private String contentFenciResult;
     private String titleFenciResult;
     private String contentFenci;

    public Datasource1() {
    }

	
    public Datasource1(String dataId) {
        this.dataId = dataId;
    }
    public Datasource1(String dataId, String dataType, String dataUrl, String dataTitle, String dataContent, Date publishTime, String dataSourceWebsite, Date grabTime, String classify, String isFenci, String contentFenciResult, String titleFenciResult, String contentFenci) {
       this.dataId = dataId;
       this.dataType = dataType;
       this.dataUrl = dataUrl;
       this.dataTitle = dataTitle;
       this.dataContent = dataContent;
       this.publishTime = publishTime;
       this.dataSourceWebsite = dataSourceWebsite;
       this.grabTime = grabTime;
       this.classify = classify;
       this.isFenci = isFenci;
       this.contentFenciResult = contentFenciResult;
       this.titleFenciResult = titleFenciResult;
       this.contentFenci = contentFenci;
    }
   
     @Id 

    
    @Column(name="DataId", unique=true, nullable=false, length=64)
    public String getDataId() {
        return this.dataId;
    }
    
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    
    @Column(name="DataType", length=32)
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    
    @Column(name="DataUrl", length=100)
    public String getDataUrl() {
        return this.dataUrl;
    }
    
    public void setDataUrl(String dataUrl) {
        this.dataUrl = dataUrl;
    }

    
    @Column(name="DataTitle", length=100)
    public String getDataTitle() {
        return this.dataTitle;
    }
    
    public void setDataTitle(String dataTitle) {
        this.dataTitle = dataTitle;
    }

    
    @Column(name="DataContent", length=65535)
    public String getDataContent() {
        return this.dataContent;
    }
    
    public void setDataContent(String dataContent) {
        this.dataContent = dataContent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PublishTime", length=19)
    public Date getPublishTime() {
        return this.publishTime;
    }
    
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    
    @Column(name="DataSourceWebsite", length=100)
    public String getDataSourceWebsite() {
        return this.dataSourceWebsite;
    }
    
    public void setDataSourceWebsite(String dataSourceWebsite) {
        this.dataSourceWebsite = dataSourceWebsite;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GrabTime", length=19)
    public Date getGrabTime() {
        return this.grabTime;
    }
    
    public void setGrabTime(Date grabTime) {
        this.grabTime = grabTime;
    }

    
    @Column(name="Classify", length=64)
    public String getClassify() {
        return this.classify;
    }
    
    public void setClassify(String classify) {
        this.classify = classify;
    }

    
    @Column(name="isFenci", length=18)
    public String getIsFenci() {
        return this.isFenci;
    }
    
    public void setIsFenci(String isFenci) {
        this.isFenci = isFenci;
    }

    
    @Column(name="ContentFenciResult", length=65535)
    public String getContentFenciResult() {
        return this.contentFenciResult;
    }
    
    public void setContentFenciResult(String contentFenciResult) {
        this.contentFenciResult = contentFenciResult;
    }

    
    @Column(name="TitleFenciResult", length=65535)
    public String getTitleFenciResult() {
        return this.titleFenciResult;
    }
    
    public void setTitleFenciResult(String titleFenciResult) {
        this.titleFenciResult = titleFenciResult;
    }

    
    @Column(name="Content_fenci", length=65535)
    public String getContentFenci() {
        return this.contentFenci;
    }
    
    public void setContentFenci(String contentFenci) {
        this.contentFenci = contentFenci;
    }




}


