package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventType generated by hbm2java
 */
@Entity
@Table(name="event_type"
    ,catalog="networkpublicopinionmap"
)
public class EventType  implements java.io.Serializable {


     private String eventTypeId;
     private String eventId;
     private String typeId;

    public EventType() {
    }

	
    public EventType(String eventTypeId) {
        this.eventTypeId = eventTypeId;
    }
    public EventType(String eventTypeId, String eventId, String typeId) {
       this.eventTypeId = eventTypeId;
       this.eventId = eventId;
       this.typeId = typeId;
    }
   
     @Id 

    
    @Column(name="event_type_id", unique=true, nullable=false, length=32)
    public String getEventTypeId() {
        return this.eventTypeId;
    }
    
    public void setEventTypeId(String eventTypeId) {
        this.eventTypeId = eventTypeId;
    }

    
    @Column(name="event_id", length=32)
    public String getEventId() {
        return this.eventId;
    }
    
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="type_id", length=32)
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }




}


