package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventFactor generated by hbm2java
 */
@Entity
@Table(name="event_factor"
    ,catalog="networkpublicopinionmap"
)
public class EventFactor  implements java.io.Serializable {


     private String eventFactorId;
     private Event event;
     private Double broseTimes;
     private Double tipNum;
     private Double replyNum;
     private Double peopleNum;
     private Date eventDate;

    public EventFactor() {
    }

	
    public EventFactor(String eventFactorId) {
        this.eventFactorId = eventFactorId;
    }
    public EventFactor(String eventFactorId, Event event, Double broseTimes, Double tipNum, Double replyNum, Double peopleNum, Date eventDate) {
       this.eventFactorId = eventFactorId;
       this.event = event;
       this.broseTimes = broseTimes;
       this.tipNum = tipNum;
       this.replyNum = replyNum;
       this.peopleNum = peopleNum;
       this.eventDate = eventDate;
    }
   
     @Id 

    
    @Column(name="event_factor_id", unique=true, nullable=false, length=32)
    public String getEventFactorId() {
        return this.eventFactorId;
    }
    
    public void setEventFactorId(String eventFactorId) {
        this.eventFactorId = eventFactorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="brose_times", precision=22, scale=0)
    public Double getBroseTimes() {
        return this.broseTimes;
    }
    
    public void setBroseTimes(Double broseTimes) {
        this.broseTimes = broseTimes;
    }

    
    @Column(name="tip_num", precision=22, scale=0)
    public Double getTipNum() {
        return this.tipNum;
    }
    
    public void setTipNum(Double tipNum) {
        this.tipNum = tipNum;
    }

    
    @Column(name="reply_num", precision=22, scale=0)
    public Double getReplyNum() {
        return this.replyNum;
    }
    
    public void setReplyNum(Double replyNum) {
        this.replyNum = replyNum;
    }

    
    @Column(name="people_num", precision=22, scale=0)
    public Double getPeopleNum() {
        return this.peopleNum;
    }
    
    public void setPeopleNum(Double peopleNum) {
        this.peopleNum = peopleNum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_date", length=19)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }




}


