package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ThemeIdea generated by hbm2java
 */
@Entity
@Table(name="theme_idea"
    ,catalog="networkpublicopinionmap"
)
public class ThemeIdea  implements java.io.Serializable {


     private String themeIdeaId;
     private Theme theme;
     private String ideaName;
     private Double ideaPercent;
     private String ideaState;

    public ThemeIdea() {
    }

	
    public ThemeIdea(String themeIdeaId) {
        this.themeIdeaId = themeIdeaId;
    }
    public ThemeIdea(String themeIdeaId, Theme theme, String ideaName, Double ideaPercent, String ideaState) {
       this.themeIdeaId = themeIdeaId;
       this.theme = theme;
       this.ideaName = ideaName;
       this.ideaPercent = ideaPercent;
       this.ideaState = ideaState;
    }
   
     @Id 

    
    @Column(name="theme_idea_id", unique=true, nullable=false, length=32)
    public String getThemeIdeaId() {
        return this.themeIdeaId;
    }
    
    public void setThemeIdeaId(String themeIdeaId) {
        this.themeIdeaId = themeIdeaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="theme_id")
    public Theme getTheme() {
        return this.theme;
    }
    
    public void setTheme(Theme theme) {
        this.theme = theme;
    }

    
    @Column(name="idea_name", length=500)
    public String getIdeaName() {
        return this.ideaName;
    }
    
    public void setIdeaName(String ideaName) {
        this.ideaName = ideaName;
    }

    
    @Column(name="idea_percent", precision=22, scale=0)
    public Double getIdeaPercent() {
        return this.ideaPercent;
    }
    
    public void setIdeaPercent(Double ideaPercent) {
        this.ideaPercent = ideaPercent;
    }

    
    @Column(name="idea_state", length=20)
    public String getIdeaState() {
        return this.ideaState;
    }
    
    public void setIdeaState(String ideaState) {
        this.ideaState = ideaState;
    }




}


