package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name="theme"
    ,catalog="networkpublicopinionmap"
)
public class Theme  implements java.io.Serializable {


     private String themeId;
     private String themeIntro;
     private String themeState;
     private double theme_hot;
     private int totalTopicNum;
     private int totalVisit;
     private int totalReply;
	 private int totalPart;
	 private String topicId;
     private Set<ThemeIdea> themeIdeas = new HashSet<ThemeIdea>(0);

    public Theme() {
    }

	
    public Theme(String themeId) {
        this.themeId = themeId;
    }
    public Theme(String themeId, String themeIntro, String themeState, Set<ThemeIdea> themeIdeas) {
       this.themeId = themeId;
       this.themeIntro = themeIntro;
       this.themeState = themeState;
       this.themeIdeas = themeIdeas;
    }
   
     @Id 

    
    @Column(name="theme_id", unique=true, nullable=false, length=32)
    public String getThemeId() {
        return this.themeId;
    }
    
    public void setThemeId(String themeId) {
        this.themeId = themeId;
    }

    
    @Column(name="theme_intro", length=65535)
    public String getThemeIntro() {
        return this.themeIntro;
    }
    
    public void setThemeIntro(String themeIntro) {
        this.themeIntro = themeIntro;
    }

    
    @Column(name="theme_state", length=20)
    public String getThemeState() {
        return this.themeState;
    }
    
    public void setThemeState(String themeState) {
        this.themeState = themeState;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="theme")
    public Set<ThemeIdea> getThemeIdeas() {
        return this.themeIdeas;
    }
    
    public void setThemeIdeas(Set<ThemeIdea> themeIdeas) {
        this.themeIdeas = themeIdeas;
    }


	public double getTheme_hot() {
		return theme_hot;
	}


	public void setTheme_hot(double theme_hot) {
		this.theme_hot = theme_hot;
	}

	public int getTotalTopicNum() {
		return totalTopicNum;
	}


	public void setTotalTopicNum(int totalTopicNum) {
		this.totalTopicNum = totalTopicNum;
	}


	public int getTotalVisit() {
		return totalVisit;
	}


	public void setTotalVisit(int totalVisit) {
		this.totalVisit = totalVisit;
	}


	public int getTotalReply() {
		return totalReply;
	}


	public void setTotalReply(int totalReply) {
		this.totalReply = totalReply;
	}


	public int getTotalPart() {
		return totalPart;
	}


	public void setTotalPart(int totalPart) {
		this.totalPart = totalPart;
	}


	public String getTopicId() {
		return topicId;
	}


	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}


}


