package com.om.domain;
// Generated 2015-11-19 11:30:47 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * WriterFactor generated by hbm2java
 */
@Entity
@Table(name="writer_factor"
    ,catalog="networkpublicopinionmap"
)
public class WriterFactor  implements java.io.Serializable {


     private String writerFactorId;
     private Writer writer;
     private Double brosesTimes;
     private Double publishTipNum;
     private Double tipReplyNum;
     private Double fansNum;
     private Double writerEmotion;
     private Double replyTipNum;
     private Double authorInfluence;
     private Double authorActiveDegree;
     private Double authorInfluence2;
     private String clusterResult;

    public WriterFactor() {
    }

	
    public WriterFactor(Writer writer) {
        this.writer = writer;
    }
    public WriterFactor(Writer writer, Double brosesTimes, Double publishTipNum, Double tipReplyNum, Double fansNum, Double writerEmotion, Double replyTipNum, Double authorInfluence, Double authorActiveDegree, Double authorInfluence2) {
       this.writer = writer;
       this.brosesTimes = brosesTimes;
       this.publishTipNum = publishTipNum;
       this.tipReplyNum = tipReplyNum;
       this.fansNum = fansNum;
       this.writerEmotion = writerEmotion;
       this.replyTipNum = replyTipNum;
       this.authorInfluence = authorInfluence;
       this.authorActiveDegree = authorActiveDegree;
       this.authorInfluence2 = authorInfluence2;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="writer"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="writer_factor_id", unique=true, nullable=false, length=32)
    public String getWriterFactorId() {
        return this.writerFactorId;
    }
    
    public void setWriterFactorId(String writerFactorId) {
        this.writerFactorId = writerFactorId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Writer getWriter() {
        return this.writer;
    }
    
    public void setWriter(Writer writer) {
        this.writer = writer;
    }

    
    @Column(name="broses_Times", precision=22, scale=0)
    public Double getBrosesTimes() {
        return this.brosesTimes;
    }
    
    public void setBrosesTimes(Double brosesTimes) {
        this.brosesTimes = brosesTimes;
    }

    
    @Column(name="publish_tip_num", precision=22, scale=0)
    public Double getPublishTipNum() {
        return this.publishTipNum;
    }
    
    public void setPublishTipNum(Double publishTipNum) {
        this.publishTipNum = publishTipNum;
    }

    
    @Column(name="tip_reply_num", precision=22, scale=0)
    public Double getTipReplyNum() {
        return this.tipReplyNum;
    }
    
    public void setTipReplyNum(Double tipReplyNum) {
        this.tipReplyNum = tipReplyNum;
    }

    
    @Column(name="fans_num", precision=22, scale=0)
    public Double getFansNum() {
        return this.fansNum;
    }
    
    public void setFansNum(Double fansNum) {
        this.fansNum = fansNum;
    }

    
    @Column(name="writer_emotion", precision=22, scale=0)
    public Double getWriterEmotion() {
        return this.writerEmotion;
    }
    
    public void setWriterEmotion(Double writerEmotion) {
        this.writerEmotion = writerEmotion;
    }

    
    @Column(name="reply_tip_num", precision=22, scale=0)
    public Double getReplyTipNum() {
        return this.replyTipNum;
    }
    
    public void setReplyTipNum(Double replyTipNum) {
        this.replyTipNum = replyTipNum;
    }

    
    @Column(name="author_influence", precision=22, scale=0)
    public Double getAuthorInfluence() {
        return this.authorInfluence;
    }
    
    public void setAuthorInfluence(Double authorInfluence) {
        this.authorInfluence = authorInfluence;
    }

    
    @Column(name="author_active_degree", precision=22, scale=0)
    public Double getAuthorActiveDegree() {
        return this.authorActiveDegree;
    }
    
    public void setAuthorActiveDegree(Double authorActiveDegree) {
        this.authorActiveDegree = authorActiveDegree;
    }

    
    @Column(name="author_influence2", precision=22, scale=0)
    public Double getAuthorInfluence2() {
        return this.authorInfluence2;
    }
    
    public void setAuthorInfluence2(Double authorInfluence2) {
        this.authorInfluence2 = authorInfluence2;
    }


	public String getClusterResult() {
		return clusterResult;
	}


	public void setClusterResult(String clusterResult) {
		this.clusterResult = clusterResult;
	}




}


